import type { Metadata } from "next";
import { getTranslations } from "next-intl/server";
import { LegalLayout, LegalSection } from "@/components/legal/LegalLayout";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "privacyPage" });
  return {
    title: t("metaTitle"),
    description: t("metaDescription"),
  };
}

const LAST_UPDATED = "April 20, 2026";

export default async function PrivacyPage() {
  const t = await getTranslations("privacyPage");

  return (
    <LegalLayout
      title={t("title")}
      subtitle={t("subtitle")}
      lastUpdated={LAST_UPDATED}
    >
      <LegalSection heading="1. Information We Collect">
        <p>We collect information you provide to us and information generated by your use of the Service.</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>
            <strong>Account data:</strong> email, phone number, password hash,
            role, and verification status.
          </li>
          <li>
            <strong>Profile data:</strong> display name, username, bio, avatar,
            locale.
          </li>
          <li>
            <strong>KYC data:</strong> full name, date of birth, address,
            identification documents (for verified sellers).
          </li>
          <li>
            <strong>Listings &amp; transactions:</strong> items you list,
            purchase, or favorite.
          </li>
          <li>
            <strong>Technical data:</strong> IP address, device information,
            timestamps, and authentication cookies.
          </li>
        </ul>
      </LegalSection>

      <LegalSection heading="2. How We Use Your Information">
        <ul className="list-disc pl-5 space-y-1">
          <li>Provide, operate, and improve the Service.</li>
          <li>Authenticate you and maintain your session.</li>
          <li>Facilitate transactions and prevent fraud.</li>
          <li>Comply with legal obligations and enforce our Terms.</li>
          <li>Send service-related notifications and, with consent, marketing.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="3. Cookies">
        <p>
          We use cookies and similar technologies to keep you signed in
          (httpOnly auth cookies), remember preferences, and understand usage.
          You can control cookies via your browser settings, but disabling them
          may break functionality such as login.
        </p>
      </LegalSection>

      <LegalSection heading="4. Data Sharing">
        <p>
          We do not sell your personal data. We share data with service
          providers under strict confidentiality (hosting, payments, analytics,
          KYC verification), with law enforcement where legally required, and
          with other users only where you choose to make data public (e.g.
          public profiles, listings).
        </p>
      </LegalSection>

      <LegalSection heading="5. Data Retention">
        <p>
          We retain your personal data for as long as your account is active
          and as needed to comply with legal obligations. When you delete your
          account, we remove or anonymize your personal data except where
          retention is required by law.
        </p>
      </LegalSection>

      <LegalSection heading="6. Your Rights">
        <ul className="list-disc pl-5 space-y-1">
          <li>Access, correct, or delete your personal data.</li>
          <li>Object to or restrict certain processing.</li>
          <li>Port your data to another service.</li>
          <li>Withdraw consent to marketing at any time.</li>
        </ul>
        <p>
          Submit requests from your account settings or email{" "}
          <a
            href="mailto:privacy@keralahub.gg"
            className="text-cyan-400 hover:underline"
          >
            privacy@keralahub.gg
          </a>
          .
        </p>
      </LegalSection>

      <LegalSection heading="7. Security">
        <p>
          We use industry-standard measures including encryption in transit,
          hashed passwords, and access controls. No system is 100% secure;
          please use a strong password and keep it confidential.
        </p>
      </LegalSection>

      <LegalSection heading="8. Changes">
        <p>
          We may update this Privacy Policy. Material changes will be
          communicated through the Service with a revised "Last updated" date.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
